// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLogs(ctx context.Context, arg CountLogsParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (CreateConnectionRow, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (CreateLogRow, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (Model, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (CreateProviderRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetConnection(ctx context.Context, arg GetConnectionParams) (GetConnectionRow, error)
	GetConnectionByProvider(ctx context.Context, arg GetConnectionByProviderParams) (Connection, error)
	GetModel(ctx context.Context, arg GetModelParams) (Model, error)
	GetModelByProxyModelID(ctx context.Context, arg GetModelByProxyModelIDParams) (Model, error)
	GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error)
	GetTotalInputTokensByProviderModelConnection(ctx context.Context) ([]GetTotalInputTokensByProviderModelConnectionRow, error)
	GetTotalOutputTokensByProviderModelConnection(ctx context.Context) ([]GetTotalOutputTokensByProviderModelConnectionRow, error)
	GetTotalPriceByProviderModelConnection(ctx context.Context) ([]GetTotalPriceByProviderModelConnectionRow, error)
	GetTotalTokensByProviderModelConnection(ctx context.Context) ([]GetTotalTokensByProviderModelConnectionRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPasswordHash(ctx context.Context, username string) (string, error)
	ListAPIKeys(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysRow, error)
	ListConnections(ctx context.Context, userID pgtype.UUID) ([]ListConnectionsRow, error)
	ListConnectionsByProviderID(ctx context.Context, arg ListConnectionsByProviderIDParams) ([]Connection, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]ListLogsRow, error)
	ListModels(ctx context.Context, userID pgtype.UUID) ([]Model, error)
	ListProviders(ctx context.Context, userID pgtype.UUID) ([]Provider, error)
	SoftDeleteConnection(ctx context.Context, arg SoftDeleteConnectionParams) error
	SoftDeleteModel(ctx context.Context, arg SoftDeleteModelParams) error
	SoftDeleteProvider(ctx context.Context, arg SoftDeleteProviderParams) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error)
}

var _ Querier = (*Queries)(nil)
