name: Build Multi-Arch Docker Image
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate tags
        id: tags
        run: |
          REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "tags=ghcr.io/${REPO_LOWER}/gen-ai-proxy-api:edge" >> $GITHUB_OUTPUT
            echo "should_build=true" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="ghcr.io/${REPO_LOWER}/gen-ai-proxy-api:latest"
            TAGS="${TAGS},ghcr.io/${REPO_LOWER}/gen-ai-proxy-api:stable"
            TAGS="${TAGS},ghcr.io/${REPO_LOWER}/gen-ai-proxy-api:${VERSION}"
            echo "tags=${TAGS}" >> $GITHUB_OUTPUT
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up QEMU
        if: steps.tags.outputs.should_build == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: steps.tags.outputs.should_build == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: steps.tags.outputs.should_build == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: steps.tags.outputs.should_build == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          platforms: linux/amd64,linux/arm64
